services:
  app:
    container_name: order
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8078:8078"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Postgres_9
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:13
    container_name: postgres-order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres_9
      POSTGRES_DB: order_service
    ports:
      - "5428:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    external: true
