CREATE TABLE orders(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INT         NOT NULL,
    status        VARCHAR(30) NOT NULL,
    creation_date TIMESTAMP        NOT NULL
);
CREATE TABLE items(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(60) NOT NULL UNIQUE,
    price NUMERIC(10, 2) NOT NULL CHECK (price >= 0)
);
CREATE TABLE order_items(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT REFERENCES orders (id),
    item_id  INT REFERENCES items (id),
    quantity INT NOT NULL CHECK (quantity > 0),
    CONSTRAINT fk_order FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,
    CONSTRAINT uc_order_item UNIQUE (order_id, item_id)
);

CREATE INDEX orders_user_id_index ON orders(user_id);
CREATE INDEX orders_status_index ON orders(status);
CREATE INDEX order_items_order_id_index ON order_items(order_id);
CREATE INDEX order_items_item_id_index ON order_items(item_id);