INSERT INTO items (name, price) VALUES ('Apple iPhone 14', 899.99);
INSERT INTO items (name, price) VALUES ('Samsung Galaxy S22', 799.49);
INSERT INTO items (name, price) VALUES ('Google Pixel 7', 699.00);
INSERT INTO items (name, price) VALUES ('OnePlus 11', 749.99);
INSERT INTO items (name, price) VALUES ('Sony WH-1000XM5', 349.90);
INSERT INTO items (name, price) VALUES ('Apple MacBook Air', 1199.99);
INSERT INTO items (name, price) VALUES ('Dell XPS 13', 999.00);
INSERT INTO items (name, price) VALUES ('Logitech MX Master 3', 99.99);
INSERT INTO items (name, price) VALUES ('Razer DeathAdder V2', 59.95);
INSERT INTO items (name, price) VALUES ('Asus ROG Laptop', 1499.00);
INSERT INTO items (name, price) VALUES ('Apple iPad Pro', 1099.00);
INSERT INTO items (name, price) VALUES ('Amazon Kindle Paperwhite', 129.99);
INSERT INTO items (name, price) VALUES ('HP LaserJet Pro', 229.00);
INSERT INTO items (name, price) VALUES ('Lenovo ThinkPad X1', 1399.00);
INSERT INTO items (name, price) VALUES ('Samsung 4K Monitor', 499.50);
INSERT INTO items (name, price) VALUES ('WD External HDD 2TB', 89.00);
INSERT INTO items (name, price) VALUES ('Crucial SSD 1TB', 99.90);
INSERT INTO items (name, price) VALUES ('Canon EOS 90D', 1199.99);
INSERT INTO items (name, price) VALUES ('GoPro HERO10', 399.99);
INSERT INTO items (name, price) VALUES ('Philips Hue Starter Kit', 179.99);
